const test = require('tape')
const compile = require('./')

const testCompile = (str, res) => test(str, t => (t.equal(compile(str), res), t.end()))

testCompile('K', 'a => b => a')
testCompile('S', 'a => b => c => a(c)(b(c))')
testCompile('KK', 'a => b => c => b')
testCompile('KS', 'a => b => c => d => b(d)(c(d))')
// testCompile('SK', 'a => b => b')
testCompile('SS', 'a => b => c => d => e => c(e)(d(e))(b)(a(b))')
testCompile('KKK', 'a => b => a')
testCompile('KKS', 'a => b => a')
// testCompile('KSK', '')
testCompile('KSS', 'a => b => c => a(c)(b(c))')
// testCompile('SKK', 'a => a')
// testCompile('SKS', '')
// testCompile('SSK', '')
// testCompile('SSS', 'a => b => c => d => b(d)(c(d))(a)(e => f => a(f)(e(f)))')
testCompile('KKKK', 'a => b => c => b')
testCompile('KKKS', 'a => b => c => d => b(d)(c(d))')

// testCompile('S(KS)K', 'a => b => c => a(b(c))')
